### ISSUE TITLE
Error: Cannot find module (...)complete-intro-to-react-v5\node_modules\parcel-bundler\bin\cli.js

### ISSUE THREAD

**Issue by mjfneto** [btholt/complete-intro-to-react-v5#102]
I come across this issue when running `npm run dev`:

```
$ npm run dev

> complete-intro-to-react-v5@1.0.0 dev C:\Users\<user>\Desktop\Área de Trabalho\Computer Science\Frontend Masters\intermediate-react-v2\complete-intro-to-react-v5
> parcel src/index.html

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'C:\Users\<user>\Desktop\Área de Trabalho\Computer Science\Frontend Masters\intermediate-react-v2\complete-intro-to-react-v5\node_modules\parcel-bundler\bin\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! complete-intro-to-react-v5@1.0.0 dev: `parcel src/index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the complete-intro-to-react-v5@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Roaming\npm-cache\_logs\2020-07-04T00_22_50_162Z-debug.log
```

**Comment by laniehei** [comment]
Just as a check, have you tried deleting the node modules and running `npm i` before running `npm run dev`?

**Comment by mjfneto** [comment]
Thank you, @laniehei. Deleting `node_modules` and running `npm install` outputs this:

```
$ npm install

> deasync@0.1.14 install C:\Users\mario\Desktop\Área de Trabalho\Computer Science\Frontend Masters\intermediate-react-v2\complete-intro-to-react-v5\node_modules\deasync
> node ./build.js


C:\Users\mario\Desktop\Área de Trabalho\Computer Science\Frontend Masters\intermediate-react-v2\complete-intro-to-react-v5\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Users\mario\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\mario\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
```

**Comment by laniehei** [comment]
Are you able to upgrade to the newest version of npm? If you are pointing to an alternative version of node-gyp than the one npm ships with, you might want to remove that as well -- you would probably know if you set that, previously. You can do this with `npm config delete node_gyp` if you know this is the case.

**Comment by laniehei** [comment]
Closing this due to inactivity. If this issue hasn't been resolved, please reopen the issue.
